### ISSUE TITLE
Automating your pipelines with Self Describing Data

### ISSUE THREAD

**Issue by gantir** [pydatabangalore/talks#1]
# Title
Automating your pipelines with Self Describing Data

## Description
Every data stream has to comply to a schema, go through basic type checks and other validation criteria. If all of your data has to go through this, why do we have to write source specific pipelines. I present an approach where the data describes itself and build generic pipelines which span across schemas.

## Duration
- [x] 30 min

## Audience
This is talk has no prerequisite, an experience with data pipelines will be useful.

## Outline
* The Problem
* Live Demo
* Self Describing Data
* Self Describing Schema
* Schema Repository
* In practice

## Additional notes
About me: I have built and scaled technology products at multiple startups. Currently building a marketing analytics solution.

---

- [ ] Don't record this talk.

**Comment by vinayak-mehta** [comment]
@gantir Can you please post the link to this talk's slides?

**Comment by vinayak-mehta** [comment]
@gantir Are you available to present this talk in the meetup next month?

**Comment by gantir** [comment]
Hi Vinayak,

Which date are you planning the next meeting?

Thanks and regards,
rAm g

*i Think, i Wait, i Fast -- Siddhartha*
http://ramjeeganti.com

**Comment by NirantK** [comment]
@gantir the next session is on the 13th of July. Would you be available? 

cc @vinayak-mehta

**Comment by gantir** [comment]
Yes. I can make it.

**Comment by vinayak-mehta** [comment]
Awesome! You can find the event details here: https://www.meetup.com/pydata-bangalore/events/262728799/

**Comment by vinayak-mehta** [comment]
I'll update the event description with your talk. See you there!

**Comment by vinayak-mehta** [comment]
@gantir Can you post the slides here?

**Comment by gantir** [comment]
@vinayak-mehta ,
Here goes the link:

https://docs.google.com/presentation/d/1R6x2K5EyQ736iTOjIS2tASGMzjhi1Q79_Io5RPlIKnU/edit?usp=sharing

**Comment by vinayak-mehta** [comment]
Thanks!
