### ISSUE TITLE
Extracting Names from multi-lingual conversation

### ISSUE THREAD

**Issue by meghanabhange** [pydatabangalore/talks#11]
# Extracting Names from multi-lingual conversation

## Description
Chatbots are an upcoming and automated way employed by businesses to communicate with their clients. An important aspect of personalising this communication is to employ natural language rather than use text boxes with strict bounds. As part of this, it is important to extract named entities(to understand the customer’s name) from messages written in unstructured, natural language. This problem is called Named Entity Recognition.

Named Entity Recognition for Chats can face several issues like inputs consisting of-

- Inconsistent grammer
- Emojies and other unexpected unicode characters
- Typos and inconsistent capitalisation.

This talk would focus on creating an efficient NER for chats by tweaking the current state of the art NER’s 

## Duration
- [ ] 30 min

## Audience
Prerequisites: This is a beginner friendly talk. Prior knowledge of NLP jargon is not expected. 

## Outline

- Introduction [5 mins]
    - Why do we need NER(Named Entity Recognition) in chatbots?
    - What are the challenges faced in NER?
- Current state-of-the-art work [5 mins]
    - Exploring NER offerings of Natural Language Libraries like spaCy and Flair(Zolando Research) ?
    - Where do these models fail for chats?
        - Humans do not always use complete grammar (E.g. What is your name? raj) 
- Dealing with chat (human conversation) specific cases [10 mins]
    - Random Capitalisation (Eg. RobErT)
    - Grammatical Errors (E.g. Name Robert mine)
    - Unicode Handling (E.g. Emojis, Accents)
    - Training model for chats 
        - FastText Model for NER and where it fails
        - Tweaking Flair NER for multiple languages and case insensitive data.
- Taking context into consideration [5 mins]
    - How Conditional Random Fields help bring context in NER tagging?
- Wrap up and questions [5 mins]
---

- [ ] Don't record this talk.

**Comment by NirantK** [comment]
Woohoo @meghanabhange 💯 🎉

**Comment by vinayak-mehta** [comment]
@meghanabhange Are you available to present it this Saturday?

**Comment by meghanabhange** [comment]
Yes. I'll be available.

**Comment by vinayak-mehta** [comment]
Awesome, see you on Saturday! I've updated the agenda on the Meetup event. You have the first talk at 10:30am.

**Comment by vinayak-mehta** [comment]
@meghanabhange Can you post the slides here?

**Comment by meghanabhange** [comment]
@vinayak-mehta 
Yepp. Here are the talk slides :)

https://docs.google.com/presentation/d/1J6655pke8YM_fuXjLmWABGLcuWh5kWD6u6v9FD22si8/edit?usp=sharing

**Comment by vinayak-mehta** [comment]
Thanks!
