### ISSUE TITLE
Transfer Learning in Computer Vision

### ISSUE THREAD

**Issue by ViswanathRavindran** [pydatabangalore/talks#14]
# Title
> Transfer Learning in Computer Vision

## Description
> This talk introduces members in the Data Science community about applying transfer learning for common Computer Vision Tasks. As an example I would demonstrate using Transfer Learning on Multi class Classification.

## Duration
- 30 min

## Audience
> Basic Python code Understanding is the only requirement and members who are working on images would certainly be the most appropriate audience. Besides I am also looking at converting 

## Outline
> The talk is a demonstration of how easy it is to work on Computer Vision Tasks using the power of transfer Learning. 
Agenda covers:
1. Intro to Transfer Learning
2. Different Computer Vision (CV) Tasks
3. Demo of Multi class Classification
4. Some of the astonishing results that are achieved in CV tasks
5. Converting a Non-CV tasks to achieve good results

A detailed outline for your talk. The more detailed the better. (1000 words)

## Additional notes
I work as a Principal Data Scientist at Idexcel where we are integrating Machine Learning into idexcel's own fintech product suite and helping some of our clients to leverage Analytics to help .
---
- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by vinayak-mehta** [comment]
@ViswanathRavindran Are you available to give this talk this Saturday? Can you also upload slides?

**Comment by ViswanathRavindran** [comment]
Hey sure, I am available to talk over this Saturday. I will upload the slides before Friday.

**Comment by vinayak-mehta** [comment]
Awesome, see you on Saturday!

**Comment by vinayak-mehta** [comment]
Thanks for the talk!
