### ISSUE TITLE
Spatial thinking with Python

### ISSUE THREAD

**Issue by Sangarshanan** [pydatabangalore/talks#2]
# Title
Spatial thinking and location intelligence 

## Description

Data can take many forms, It could be a text an image or maybe it is a bunch of coordinates. Though computer vision and natural language processing have hit it off spatial data science doesn’t get the attention it deserves. Spatial data has both social and industrial impact. Spatial data is useful in agriculture and for observing weather patterns to predict natural disasters. It is also very important for industries that deal with logistics and supply chain management. So in this talk I would like to focus on spatial data and how effective use of location intelligence can add immense value  

## Duration
- [x] 30 min
- [ ] 45 min

## Audience

This is a beginner friendly talk. Basic Python knowledge would be more than necessary

## Outline

   - What is spatial thinking and the state of location intelligence 
   - The need for spatial analytics 
   -  Spatial support from databases and packages. Why Osgeo is awesome
   -  Problems that can be solved and processes that can be optimized with spatial data
   -  Talking some cool spatial use-cases by Uber, Airbnb, Walmart etc  

---

- [ ] Don't record this talk.

**Comment by vinayak-mehta** [comment]
@Sangarshanan You can give this talk at a future meetup. I've reopened this.

**Comment by vinayak-mehta** [comment]
See you on 21st September!

**Comment by vinayak-mehta** [comment]
Thanks for the talk!
