### ISSUE TITLE
OpenStreetMap Data Processing with Python

### ISSUE THREAD

**Issue by ramyaragupathy** [pydatabangalore/talks#22]
# Title
OpenStreetMap Data Processing with Python

## Description
[Openstreetmap](https://www.openstreetmap.org/), with its community of more than 5 million contributors, is the wikipedia of maps. If you find your favorite store missing on the map, you can directly add it to OpenStreetMap (OSM). It’s for everyone, and anyone interested can create their own maps using the data. If needed the whole world data can be downloaded offline. It is a highly detailed data set that can be used for data science and exploratory data analysis. This presentation covers an overview of the whole data pipeline with OSM and Python.

## Duration
- [x] 45 min

## Audience
Beginner friendly

## Outline
* Introduce OpenStreetMap (OSM) and its data structure
* Various methods to retrieve OSM data
* Data Transformation with GeoPandas
* Interactive visualization with Folium/mapboxgl

## Additional notes

https://twitter.com/ramya_ragupathy

**Comment by vinayak-mehta** [comment]
@ramyaragupathy Are you available to present this talk on Nov 9?

**Comment by ramyaragupathy** [comment]
Thanks for accepting the talk @vinayak-mehta - I will be out of town for the next two weekends. December should be good for me.

**Comment by vinayak-mehta** [comment]
:+1:

**Comment by vinayak-mehta** [comment]
@ramyaragupathy Are you available to present this talk on Dec 14? https://www.meetup.com/pydata-bangalore/events/266804685/

**Comment by ramyaragupathy** [comment]
Yes @vinayak-mehta - let's commit on that date.

**Comment by vinayak-mehta** [comment]
Awesome! Assigning slot 1 of the Python track, see you on Dec 14 :)

**Comment by vinayak-mehta** [comment]
Updated the agenda: https://www.meetup.com/pydata-bangalore/events/266804685/

See you on Saturday!

**Comment by TrigonaMinima** [comment]
Hey @ramyaragupathy, would you be available to give the talk on 18th Jan?

**Comment by ramyaragupathy** [comment]
Yes - please go ahead scheduling this for the event

**Comment by TrigonaMinima** [comment]
Hey @ramyaragupathy, you are scheduled to speak in the 4th slot: 12:30 pm - 1:15 pm. See you there.

**Comment by ramyaragupathy** [comment]
Thank you!

**Comment by TrigonaMinima** [comment]
https://docs.google.com/presentation/d/1rC7WFn_w_QZaoJjriwvk3ykRiWKny1ip4pZXex82amo/mobilepresent#slide=id.g6454da2949_1_119

**Comment by TrigonaMinima** [comment]
Thanks for the talk. See you in the future talks.
