### ISSUE TITLE
Streaming Data Pipelines with Apache Beam

### ISSUE THREAD

**Issue by ttanay** [pydatabangalore/talks#26]
# Title
Streaming Data Pipelines with Apache Beam

## Description
Concepts involved in writing Streaming Data Pipelines with example using Apache Beam.
## Duration
- [X] 30 min
- [ ] 45 min

## Audience
Intermediate

## Outline
-    Introduction
-   Apache Beam Model    
	-   Unbounded and Bounded Data
	-   Event time - Processing time Skew
       -   What/When/Where/How
	-   Windowing
	-   Watermarks  
	-   Triggers
	-   Accumulation Mode
-  Data Processing in Apache Beam
	-   Core PTransforms
	-   Beam execution model
-   Applications / Use-cases
-    Contributing
-   More Resources

## Additional notes  
GSoC '19 student with Apache Beam. Intern @clarisights. Previous @atlanhq

---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by ttanay** [comment]
Thanks @vinayak-mehta !

**Comment by vinayak-mehta** [comment]
@ttanay Are you available to present this talk on Dec 14? https://www.meetup.com/pydata-bangalore/events/266804685/

**Comment by ttanay** [comment]
Yes :)

**Comment by vinayak-mehta** [comment]
Updated the agenda: https://www.meetup.com/pydata-bangalore/events/266804685/

See you on Saturday!

**Comment by ttanay** [comment]
Slides: https://docs.google.com/presentation/d/1vst7kJnBCVrdqw2_6__aZbWsGdeU9ulWnklSDMUjLpQ/edit?usp=sharing

**Comment by amrrs** [comment]
Thanks @ttanay  Updated here - https://github.com/pydatabangalore/talks/blob/master/README.md 

Please check!

**Comment by vinayak-mehta** [comment]
Thanks for the talk @ttanay!
