### ISSUE TITLE
Hosting PyData in ABInBev office

### ISSUE THREAD

**Issue by ShashiBsSingh** [pydatabangalore/talks#28]
Dear Team,

We would be very happy to host the January meetup in our [Global Analytics Center office](https://goo.gl/maps/t36sfJUZSYpTphdB8) of AB InBev in Vittal Mallya Road, next to UB City. Let me know what needs to be done and how can we start the process for the same.

Regards;
Shashi(+91 9008922044)

**Comment by NirantK** [comment]
@vinayak-mehta is the right person to talk to Shashi

Find the other team members on Slack at #team. 

https://join.slack.com/t/pydatabangalore/shared_invite/enQtNjkzMjA5MTA4MDUyLTE2OWQ4MjFkMGZhNDFjM2IxNmYwM2JkZTdjOGNhNmI5Yzg1Yzk3MTVlMTZjOTMwMWJhYzFkZDZkN2ZjNzdiNDg

**Comment by vinayak-mehta** [comment]
@ShashiBsSingh Sorry for the late reply. How many people can the AB InBev office accommodate?

We'll also require the following things:
- Screen
- Projector
- Microphone
- Snacks / tea / coffee

**Comment by ShashiBsSingh** [comment]
@vinayak-Mehta, accommodating people shouldn't be an issue as we've multiple rooms/audi of varying capacity(ranging from 20-100). Also the other mentioned stuffs can be arranged as well. We can discuss the details over the call.

Regards;
Shashi(+91 9008922044)

**Comment by vinayak-mehta** [comment]
We've finalized a venue for December's meetup. We'll get back to you in Janurary! Thanks for offering the space :)

**Comment by ShashiBsSingh** [comment]
Sure @vinayak-mehta , that works.
