### ISSUE TITLE
Interpretability: Cracking open the Black Box

### ISSUE THREAD

**Issue by manujosephv** [pydatabangalore/talks#30]
# Title
> Interpretability: Cracking open the Black Box

## Description
> A review of Interpretable models, how to interpret them and common pitalls. And then move on to look at techniques to explain black box models and how to correctly interpret the results.

## Duration
- [ ] 30 min
- [x] 45 min

## Audience
> Talk is for intermediate as well as experienced ML practitioners.
    Prerequisites:
         1. Basic Knowldge of Machine Learning Algorithms
         2. Python (soft requirement as the examples are in Python, but the concepts are universal)

## Outline
>  As the machine learning field matured and more and more models have started to be in use in the wild, the need for explainability has become more and more important. The talk would be structured as below
- What is Interpretability?
- Interpretable Models - How to interpret them?
- Blackbox model explanation techniques
    - Mean Decrease in Impurity,
    - Permutation Importance
    - Partial Dependence Plots
    - LIME
    - Shapely Values and SHAP

## Additional notes
> https://www.linkedin.com/in/manujosephv/

---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by TrigonaMinima** [comment]
Hi @manujosephv thanks for the proposal.

- Since we have a mixed crowd - beginners to advanced - it'd be good if you could add a little explanation to the models you're going to present.
- Also it'd be good if you make it clear in the outline what kind of models (cv, nlp, traditional ml algos) you're going to target. If it's going to generic then i guess it's fine.
- Would you be available for the talk on 18th Jan?

**Comment by NirantK** [comment]
Brilliant topic set Manu! Sad that I'd have to miss this :(

**Comment by manujosephv** [comment]
The talk would be centered around Traditional ML Algos, although some of the techniques can be used for CV and NLP problems as well.
Explanation Techniques - Mean Decrease in Impurity, Leave One Co-variate Out Importance, Permutation Importance, Partial Dependence Plots, ICE plots, Locally Interpretable Model Agnostic Explanations (LIME), Shapely Values

- Would you be available for the talk on 18th Jan?
Yes.

**Comment by TrigonaMinima** [comment]
Awesome! Your talk is final for the event. Putting you on the 3rd slot - 11:45 AM to 12:30 PM. See you there.

**Comment by TrigonaMinima** [comment]
Hey @manujosephv, can you please upload the ppt somewhere on cloud (google docs, google drive, slide share, github) and share the link here? Need to update the readme with the links to the slides.

**Comment by manujosephv** [comment]
@TrigonaMinima I've uploaded the ppt in this link
https://drive.google.com/open?id=1GnpWyHXNNx-wkRgNFFvzz-iVE69ML-bV

@NirantK Even if you missed the session, if you can sit through a long three part blog, you can get the information here... 
https://deep-and-shallow.com/2019/11/13/interpretability-cracking-open-the-black-box-part-i/
https://deep-and-shallow.com/2019/11/16/interpretability-cracking-open-the-black-box-part-ii/
https://deep-and-shallow.com/2019/11/24/interpretability-cracking-open-the-black-box-part-iii/

**Comment by TrigonaMinima** [comment]
@manujosephv I dont think the ppt is publicly available. Please make it public.

**Comment by manujosephv** [comment]
Oops.. have made it public..

**Comment by TrigonaMinima** [comment]
Yeah i can see it now. Thanks. See you in the future talks.
