### ISSUE TITLE
Understanding Extractive Text Summarization

### ISSUE THREAD

**Issue by thejasbhat** [pydatabangalore/talks#31]
# Title
> Understanding Extractive Text Summarization

## Description
> A glance on evolution of extractive summarization techniques from word frequency based to fine tuning of BERT.

## Duration
- [x] 30 min
- [ ] 45 min
## Audience
Talk is for beginners as well as intermediate NLP practitioners.

## Prerequisites:
1. Familiarity of NLP terminologies.
2. Basic understanding of Deep-learning techniques.
3. Basic Python

## Outline
> As the use of ML/AI technology is growing there is a need to tap the potential of unstructured data. One of the primary task of NLP is to get the summary and key words from a text corpus.
Although Abstractive summarization is desirable at this point of time the readability of lengthy content created by algorithms is not production ready. Extractive summarization with better
readability is a implementable solution for summarization problem.

## Topics
What is summarization?
Importance of text summarization
Type of text summarizations
Why Extractive
Evolution from word frequency based to text rank to BERTSum.
Explain BERT-Sum approach in detail : Use of Attention Mechanism

- [x] Don't record this talk.

**Comment by TrigonaMinima** [comment]
Hey @thejasbhat are you available to present on 29th Feb?

**Comment by thejasbhat** [comment]
Hi @TrigonaMinima out of town on 29th.

**Comment by TrigonaMinima** [comment]
@thejasbhat cool. Thanks for the response. Let us know if you'd be willing to present in the future date. Will reopen the issue.
