### ISSUE TITLE
A look at state-of-the-art dimensionality reduction techniques

### ISSUE THREAD

**Issue by tamojit-maiti** [pydatabangalore/talks#32]
# Title
A look at state-of-the-art dimensionality reduction techniques

## Description
A glance at dimensionality reduction techniques applied to public datasets

## Duration
- [x] 30 min
- [ ] 45 min

## Audience
Talk is for beginners as well as for intermediate data scientists

## Outline
With the advent of large amounts of data, it can be difficult to develop a feel for the data as well as identify latent features that possess most predictive power. We take a look at traditional matrix-based factorization approaches to dimensionality reduction, introduce the audience to current state-of-the-art manifold-based approaches and compare their performances on popular publicly available datasets. 

## Topics
1. Dimensionality Reduction, what and why?
2. Overview of Matrix-based factorization methods 
3. Introduction to Manifold based Approaches
4. t-SNE : Current state-of-the-art technique
5. Performance comparison of the two approaches on public datasets

## Additional notes
https://www.linkedin.com/in/tamojit-maiti-635691157/

---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by TrigonaMinima** [comment]
@tamojit-maiti would you be available to present this talk in the 18th Jan meetup?

**Comment by tamojit-maiti** [comment]
> @tamojit-maiti would you be available to present this talk in the 18th Jan meetup?

Yes, I'll be available on 18th Jan to present this talk

**Comment by TrigonaMinima** [comment]
Great. You are up for the second slot: 11:00 AM to 11:30 AM. See you there.

**Comment by tamojit-maiti** [comment]
> Great. You are up for the second slot: 11:00 AM to 11:30 AM. See you there.

@TrigonaMinima Sure, thanks! I'll be there.

**Comment by TrigonaMinima** [comment]
Hey @tamojit-maiti, can you please upload the presentation somewhere online (google drive, google docs, github, slideshare) and share the link here? Need to update the readme.

**Comment by tamojit-maiti** [comment]
@TrigonaMinima I have uploaded them on my GitHub. Please have a look

**Comment by TrigonaMinima** [comment]
https://github.com/tamojit-maiti/PyData-Dimension_Reduction-Jan-2020

**Comment by TrigonaMinima** [comment]
Thanks for the talk. See you in the future talks.
