### ISSUE TITLE
Learn Apache Spark Using PySpark

### ISSUE THREAD

**Issue by originalankur** [pydatabangalore/talks#4]
# Learn Apache Spark - PySpark

## Description
Apache Spark is a distributed general-purpose cluster-computing framework. The talk teaches the basics of Spark. A hands-on code snippet driven style of teaching will allow Python developers to quickly learn ramp up the basics and working of Spark. 

## Duration
- [x] 45 min

## Knowledge of
- Python 3.5+   

## Outline
- Installation
- Hello World
- Read a large CSV and run basic computation using 
  - RDD
  - dataframes  
- Data Transformations
   - Filter
   - Flatmap
   - Sample
   - Union
   - Intersection
   - Distinct
   - Cartesian
   - Pipe
   - Coalesce
   - Repartition
   - .agg() 
   - .sql() 
- Persisting Data
- Datasets & SQL
- Streaming Data into Spark

## Additional notes
Linkedin Profile - https://www.linkedin.com/in/ankurgupta1982/

**Comment by vinayak-mehta** [comment]
@originalankur Can you please post the link to this talk's slides?
