### ISSUE TITLE
Machine Learning Bias

### ISSUE THREAD

**Issue by amrrs** [pydatabangalore/talks#9]
# Title
Machine Learning Bias

## Description
ML Bias has become a global discussion yet the awareness among developer/Data science community around us doesn't seem significant. This is an attempt to spread the word out.

## Duration
- [ ] 30 min
- [x] 45 min

## Audience
ML / Data Science Practitioners 

## Outline
A model wouldn’t lie unless the Machine Learning Engineer want it to lie. Humans are filled with unconscious biases and when these are fed into Machine to Learn in the form of Data, the resulting AI model wouldn't be `fair` enough without Biases. This talk tries to introduce you to the world of Machine Learning Bias. 

## Additional notes
https://speakerdeck.com/amrrs/machine-learning-bias

---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by vinayak-mehta** [comment]
@amrrs Is this a 45 minute talk? The markdown checkbox is not marked properly. Editing the description.

**Comment by amrrs** [comment]
@vinayak-mehta 45 min would be decent but can be customized to do with 30 mins

**Comment by vinayak-mehta** [comment]
@amrrs Would you be available for the next meetup on 13th July? https://www.meetup.com/pydata-bangalore/events/262728799/

**Comment by amrrs** [comment]
@vinayak-mehta  Sorry date clash with R meetup https://www.meetup.com/BengaluRu-use-R-gRoup/events/262893638/

**Comment by vinayak-mehta** [comment]
@amrrs Are you available to give this talk this Saturday?

**Comment by vinayak-mehta** [comment]
@amrrs See you on Saturday!

**Comment by vinayak-mehta** [comment]
Thanks for the talk!
